{{config(materialized='view')}}

SELECT
    TO_HEX(SHA256(CONCAT(Name, '-', CAST(Year AS STRING)))) AS player_id,
    SAFE_CAST(Rank AS INT64) AS rank,
    SAFE_CAST(Year AS INT64) AS season_year,
    UPPER(TRIM(Name)) AS player_name,
    UPPER(TRIM(Position)) as position,
    SAFE_CAST(AGE AS INT64) AS age,
    SAFE_CAST(WINS AS INT64) AS wins,
    SAFE_CAST(Losses AS INT64) AS losses,
    SAFE_CAST(Winning_Percentage AS FLOAT64) AS winning_percentage,
    SAFE_DIVIDE(earned_runs * 9, NULLIF(innings_pitched,0)) AS earned_runs_average,
    SAFE_CAST(Games_Played AS INT64) AS games_played,
    SAFE_CAST(Games_Started AS INT64) AS games_started,
    SAFE_CAST(Games_Finished AS INT64) AS games_finished,
    SAFE_CAST(Complete_Games AS INT64) AS complete_games,
    SAFE_CAST(Shutouts AS INT64) AS shutouts,
    SAFE_CAST(Saves AS INT64) AS saves,
    SAFE_CAST(Innings_Pitched AS FLOAT64) AS innings_pitched,
    SAFE_CAST(Hits_Allowed AS INT64) AS hits_allowed,
    SAFE_CAST(Runs_Allowed AS INT64) AS runs_allowed,
    SAFE_CAST(Earned_Runs AS INT64) AS earned_runs,
    SAFE_CAST(Home_Runs_Allowed AS INT64) AS home_runs_allowed,
    SAFE_CAST(Walks_Allowed AS INT64) AS walks_allowed,
    SAFE_CAST(Intentional_Walks_Allowed AS INT64) AS intentional_walks_allowed,
    SAFE_CAST(Strikeouts AS INT64) AS strikeouts,
    SAFE_CAST(Hit_By_Pitch AS INT64) AS hit_by_pitch,
    SAFE_CAST(balks AS INT64) AS balks,
    SAFE_CAST(Wild_Pitches AS INT64) AS wild_pitches,
    SAFE_CAST(Batters_Faced AS INT64) AS batters_faced,
    SAFE_DIVIDE((13*home_runs_allowed)+(3*(walks_allowed+hit_by_pitch))-(2*strikeouts),(innings_pitched+3.1)) AS fielding_independent_pitching,
    SAFE_CAST(Walks_Hits_Per_Inning_Pitched AS FLOAT64) AS walks_hits_per_inning_pitched,
    SAFE_CAST(Hits_Per_Nine_Innings AS FLOAT64) AS hits_per_nine_innings,
    SAFE_CAST(Home_Runs_Per_Nine_Innings AS FLOAT64) AS homeruns_per_nine_innings,
    COALESCE(SAFE_DIVIDE(walks_allowed * 9, NULLIF(innings_pitched,0)),0) AS walks_per_nine_innings,
    SAFE_CAST(Strikeouts_Per_Nine_Innings AS FLOAT64) AS strikeouts_per_nine_innings,
    SAFE_CAST(Strikeout_Walk_Ratio AS FLOAT64) AS strikeout_walk_ratio,
    UPPER(TRIM(Dominant_Hand)) AS dominant_hand,
    Switch_Hitter as switch_hitter
FROM {{source('padres_raw', 'pitching')}}